# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  # Solid Cable (Action Cable’s DB-backed adapter)
  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  # (optional but recommended for Rails 8 defaults)
  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
